# Generated by Django 5.0.4 on 2024-05-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opiniones', '0002_opinion_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='reseña',
            field=models.TextField(blank=True, null=True, verbose_name='reseña'),
        ),
    ]
